print("class: A user-defined compound type. A class can also be thought of as a")
print("template for the objects that are instances of it.")
print("instantiate: To create an instance of a class.")
print("instance: An object that belongs to a class.")
print("object: A compound data type that is often used to model a thing or concept")
print("in the real world.")
print("constructor: A method used to create new objects.")
print("attribute: One of the named data items that makes up an instance.")
print("shallow equality: Equality of references, or two references that point to the")
print("same object.")
print("deep equality: Equality of values, or two references that point to objects that")
print("have the same value.")
print("shallow copy: To copy the contents of an object, including any references to")
print("embedded objects; implemented by the copy function in the copy module.")
print("deep copy: To copy the contents of an object as well as any embedded objects, and any objects embedded in them, and so on; implemented by the")
print("deepcopy function in the copy module.")